In [2]:
import numpy as np 
from sklearn import datasets 
from sklearn.model_selection import train_test_split 


In [33]:
class Adaline(object):
    def __init__(self ,eta =0.01,n_iter=50,random_state=1):
        self.eta=eta
        self.n_iter=n_iter
        self.random_state=random_state
        
    def fit(self,x,y ):
        rgen=np.random.RandomState(self.random_state)
        self.w_ =rgen.normal(loc=0.0,scale=0.01,size=1+x.shape[1])
        self.cost_ = []
        for i in range(self.n_iter):
            net_input=self.net_input(x)
            output=self.activation(net_input)
            errors=(y- output)
            self.w_[1:] += self.eta * x.T.dot(errors)
            self.w_[0]+=self.eta *errors.sum()
            cost=(errors**2).sum()/2.
            self.cost_.append(cost)
        return self 
    def net_input(self,x):
        return np.dot(x,self.w_[1:]) +self.w_[0]
    
    def activation(self,x ):
        return x 
    
    def predict(self,x):
        return np.where(self.activation(self.net_input(x)) >=  0.0,1,-1)
        

In [29]:
data=datasets.load_diabetes() 
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target)
x_train.shape,x_test.shape 

((331, 10), (111, 10))

In [53]:
ada1 = Adaline(eta=0.0001,n_iter=10)
ada1.fit(x_train,y_train)

In [54]:
y_pred=ada1.predict(x_test)

In [55]:
ada1.activation(x_train)

array([[ 0.00538306, -0.04464164,  0.05954058, ...,  0.05091436,
        -0.00422151, -0.03007245],
       [-0.01277963, -0.04464164,  0.06061839, ...,  0.03430886,
         0.07020738,  0.00720652],
       [ 0.01628068, -0.04464164, -0.04500719, ..., -0.0763945 ,
        -0.04257085,  0.04034337],
       ...,
       [ 0.01264814, -0.04464164,  0.00672779, ..., -0.03764833,
        -0.01811369, -0.09220405],
       [-0.09996055, -0.04464164, -0.02345095, ..., -0.03949338,
        -0.01811369, -0.05078298],
       [-0.04910502,  0.05068012, -0.02452876, ...,  0.02840468,
         0.01919647,  0.01134862]])

In [56]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [58]:
data1=datasets.load_iris()
xtrain,xtest,ytrain,ytest=train_test_split(data.data,data.target)



In [60]:
ada1.fit(xtrain,ytrain)
y_pred2 =ada1.predict(xtest)
y_pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])