In [3]:
#forward propogation with hidden layer 
import numpy as np 

In [4]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T


In [5]:
#putting weights random between 1 and -1 
weights = 2*np.random.random((2,1))-1  
bias =2*np.random.random(1)-1
weights ,bias 

(array([[0.48453954],
        [0.00842756]]),
 array([0.03483281]))

In [6]:
def seg(z):
    return 1/(1+np.exp(-z))

In [7]:
def segDerivative(z):
    return seg(z)*(1-seg(z))

In [8]:
lr=0.01
for iter in range(10000):
    output0 = x
    output = seg(np.dot(output0, weights) + bias)

    first_term = output - y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = segDerivative(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.array([[0.0],[0.0]])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
output = seg(np.dot(x, weights) + bias)
weights, bias, output

(array([[2.63149852],
        [2.63025495]]),
 array([-4.07169594]),
 array([[0.01676267],
        [0.1913223 ],
        [0.19151478],
        [0.76675135]]))

In [9]:
#in this code we are replacing 'for ' loops 
lr=0.01
for iter in range(10000):
    output0 = x
    output = seg(np.dot(output0, weights) + bias)

    first_term = output - y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = segDerivative(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape
    changes = np.dot(output0.T,first_two)        
    weights = weights - lr*changes
    bias_change =np.sum(first_two)
    bias = bias - lr * bias_change
output = seg(np.dot(x, weights) + bias)
weights, bias, output

(array([[3.49700384],
        [3.49695516]]),
 array([-5.35431812]),
 array([[0.00470545],
        [0.13501072],
        [0.1350164 ],
        [0.83748606]]))